name: news_app_with_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  # State management getx
  get: 4.6.5
  flutter: 
    sdk: flutter
  #for firebase authentication and cloud
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  #cache management
  shared_preferences:
  flutter_screenutil:
  connectivity_plus:
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

